// Loaded at runtime from /snapshot.json. Keep this file small; real content
// lives in public/snapshot.json (regenerated by `npm run snapshot`).
export type SnapshotFile = {
  path: string;
  language: string;
  content: string;
  bytes: number;
};

export type Snapshot = {
  generatedAt: string;
  files: SnapshotFile[];
};

let cache: Snapshot | null = null;

export async function loadSnapshot(): Promise<Snapshot> {
  if (cache) return cache;
  try {
    const res = await fetch('/deck/snapshot.json', { cache: 'force-cache' });
    if (!res.ok) throw new Error(`snapshot ${res.status}`);
    const json = (await res.json()) as Snapshot;
    cache = json;
    return json;
  } catch {
    return { generatedAt: new Date().toISOString(), files: [] };
  }
}

export function findFile(snap: Snapshot, path: string): SnapshotFile | undefined {
  return snap.files.find((f) => f.path === path || f.path.endsWith(path));
}
